version: 2

vm_settings: &vm_settings
  docker:
    - image: circleci/node:latest-browsers
  working_directory: ~/app

install_restore_cache: &install_restore_cache
  name: Restore cached dependencies
  keys:
    - dependencies-{{ checksum "package-lock.json" }}
    - dependencies

install_run: &install_run
  name: Install dependencies with NPM
  command: npm ci

install_save_cache: &install_save_cache
  name: Cache installed dependencies
  paths:
    - ~/.cache
  key: dependencies-{{ checksum "package-lock.json" }}

jobs:
  test:
    <<: *vm_settings
    steps:
      - checkout
      - restore_cache: *install_restore_cache
      - run: *install_run
      - save_cache: *install_save_cache
      - run:
          name: Run tests
          command: npm run test:unit
      - store_artifacts:
          path: tests/unit/coverage

  docs:
    <<: *vm_settings
    steps:
      - checkout
      - restore_cache: *install_restore_cache
      - run: *install_run
      - save_cache: *install_save_cache
      - run: sh ./docs/deploy.sh

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test:
        filters:
          branches:
            only: master
      - docs:
        requires:
          - test
        filters:
          branches:
            only: master
